services:
  backend:
    build: ./backend
    container_name: plant-backend
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: plant-frontend
    ports:
      - "80:80"
    depends_on:
      - backend